"""Add published_date to books

Revision ID: 26130b44a03a
Revises: 482e6a5d936d
Create Date: 2025-08-21 23:44:19.691388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26130b44a03a'
down_revision: Union[str, None] = '482e6a5d936d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('published_date', sa.String(), nullable=True))
    op.add_column('books', sa.Column('page_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'page_count')
    op.drop_column('books', 'published_date')
    # ### end Alembic commands ###
