"""Add price column to books

Revision ID: 45fa3ea41a9a
Revises: 42591218e1a8
Create Date: 2025-08-06 22:29:16.500688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45fa3ea41a9a'
down_revision: Union[str, None] = '42591218e1a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('description', sa.String(), nullable=True))
    op.add_column('books', sa.Column('seller_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'users', ['seller_id'], ['id'])
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'seller_id')
    op.drop_column('books', 'description')
    op.drop_column('books', 'price')
    # ### end Alembic commands ###
