"""add google fields to books

Revision ID: 482e6a5d936d
Revises: 45fa3ea41a9a
Create Date: 2025-08-18 22:30:13.746198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '482e6a5d936d'
down_revision: Union[str, None] = '45fa3ea41a9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('google_id', sa.String(), nullable=True))
    op.add_column('books', sa.Column('source', sa.String(), nullable=True))
    op.alter_column('books', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'books', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='unique')
    op.alter_column('books', 'price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('books', 'source')
    op.drop_column('books', 'google_id')
    # ### end Alembic commands ###
